// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqjFSy-MMZrhfcOhRgr2paQsXNNZZihSM',
    appId: '1:6229665685:web:0aaca0e96347aba190b89c',
    messagingSenderId: '6229665685',
    projectId: 'food-chain-saas',
    authDomain: 'food-chain-saas.firebaseapp.com',
    storageBucket: 'food-chain-saas.appspot.com',
    measurementId: 'G-PFT2SK7WGX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD98z5ljupC8JMiuB6mCIMb3-jKYDyGIT0',
    appId: '1:6229665685:android:ac995415ebda58b590b89c',
    messagingSenderId: '6229665685',
    projectId: 'food-chain-saas',
    storageBucket: 'food-chain-saas.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuuwmFCmnhnU_rD5VSsUQhDtXZ28NSZ50',
    appId: '1:6229665685:ios:eb03a087a4a9f59c90b89c',
    messagingSenderId: '6229665685',
    projectId: 'food-chain-saas',
    storageBucket: 'food-chain-saas.appspot.com',
    iosBundleId: 'com.example.foodchainFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuuwmFCmnhnU_rD5VSsUQhDtXZ28NSZ50',
    appId: '1:6229665685:ios:eb03a087a4a9f59c90b89c',
    messagingSenderId: '6229665685',
    projectId: 'food-chain-saas',
    storageBucket: 'food-chain-saas.appspot.com',
    iosBundleId: 'com.example.foodchainFlutter',
  );
}
